USE teufuturo;

SET character_set_client = utf8;
SET character_set_connection = utf8;
SET character_set_results = utf8;
SET collation_connection = utf8_general_ci;

-- ---------- DOMAIN TABLES ----------
create table ESCOLA
(
    ID int unsigned auto_increment primary key,
    NOME varchar(125) not null
);

create table SPONSOR
(
    ID int unsigned auto_increment primary key,
    NOME varchar(125) not null
);

create table ANO_ENSINO_MEDIO
(
    ID int unsigned auto_increment primary key,
    ANO varchar(25) not null
);
-- ----------------------------------------

INSERT INTO ESCOLA (ID, NOME) VALUES (1, 'COLEGIO ESTADUAL JOAQUIM FAGUNDES DOS REIS');
INSERT INTO ESCOLA (ID, NOME) VALUES (2, 'INSTITUTO ESTADUAL CECY LEITE COSTA');
INSERT INTO ESCOLA (ID, NOME) VALUES (3, 'INSTITUTO ESTADUAL CARDEAL ARCOVERDE');
INSERT INTO ESCOLA (ID, NOME) VALUES (4, 'ESC EST EDU BASICA NICOLAU DE ARAUJO VERGUEIRO (EENAV)');
INSERT INTO ESCOLA (ID, NOME) VALUES (5, 'ESCOLA ESTADUAL DE ENSINO MEDIO ERNESTO TOCCHETTO');
INSERT INTO ESCOLA (ID, NOME) VALUES (6, 'ESC EST ENS MEDIO ADELINO PEREIRA SIMOES');
INSERT INTO ESCOLA (ID, NOME) VALUES (7, 'ESCOLA ESTADUAL DE ENSINO MEDIO PROTASIO ALVES');
INSERT INTO ESCOLA (ID, NOME) VALUES (8, 'ESC EST ENSINO MEDIO GENERAL PRESTES GUIMARAES');
INSERT INTO ESCOLA (ID, NOME) VALUES (9, 'ESCOLA ESTADUAL DE EDUCACAO BASICA MONTEIRO LOBATO');
INSERT INTO ESCOLA (ID, NOME) VALUES (10, 'ESCOLA ESTADUAL DE ENSINO MEDIO ANTONINO XAVIER E OLIVEIRA');
INSERT INTO ESCOLA (ID, NOME) VALUES (11, 'ESC EST ENSINO MEDIO MARIO QUINTANA');
INSERT INTO ESCOLA (ID, NOME) VALUES (12, 'ESC EST ENS MEDIO ALBERTO PASQUALINI');
INSERT INTO ESCOLA (ID, NOME) VALUES (13, 'ESC EST ENSINO MEDIO ANNA LUISA FERRAO TEIXEIRA');
INSERT INTO ESCOLA (ID, NOME) VALUES (14, 'EEEM MARIA DOLORES FREITAS BARROS');
INSERT INTO ESCOLA (ID, NOME) VALUES (15, 'COLEGIO TIRADENTES DA BRIGADA MILITAR');
INSERT INTO ESCOLA (ID, NOME) VALUES (16, 'ESC EST ENS MEDIO PROFESSORA EULINA BRAGA');
INSERT INTO ESCOLA (ID, NOME) VALUES (17, 'EEEM SENHOR DOS CAMINHOS');
INSERT INTO ESCOLA (ID, NOME) VALUES (18, 'INSTITUTO ESTADUAL SANTO TOMÁS DE AQUINO - IESTA');
INSERT INTO ESCOLA (ID, NOME) VALUES (19, 'EEEM ANCHIETA');

INSERT INTO SPONSOR (ID, NOME) VALUES (1, 'Compasso');
INSERT INTO SPONSOR (ID, NOME) VALUES (2, 'Atua');
INSERT INTO SPONSOR (ID, NOME) VALUES (3, 'Razor');

INSERT INTO ANO_ENSINO_MEDIO (ID, ANO) VALUES (1, '2º ano');
INSERT INTO ANO_ENSINO_MEDIO (ID, ANO) VALUES (2, '3º ano');
